version: "3"

services:
  sqlite:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
  app:
    build: app
    ports:
      - "8000:8000"
    volumes:
      - ./db:/root/db/
    depends_on:
      - sqlite
    restart: always
